name: azienda-agricola-maggini
services:
  web:
    env_file:
      - .env
    image: node:${NODEJS_VERSION}
    working_dir: /home/node/app
    container_name: nextjs
    networks:
      - mynetwork
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db
    command: sh -c "npm i && npm run build && npm run start"
    restart: unless-stopped
  http-db:
    env_file:
      - .env
    image: node:${NODEJS_VERSION}
    working_dir: /home/node/app
    container_name: http-db
    networks:
      - mynetwork
    ports:
      - 3001:3001
    volumes:
      - .:/home/node/app
    depends_on:
      - db
    command: sh -c "npm i && npm run http-db"
    restart: unless-stopped
  db:
    image: mysql:8.0
    container_name: db
    networks:
      - mynetwork
    env_file:
      - .env
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - dbdata:/var/lib/mysql
    restart: unless-stopped
volumes:
  dbdata:
    name: azienda-agricola-maggini-dbdata
networks:
  mynetwork:
    driver: bridge
