import type {Metadata} from "next";
import {Inter} from "next/font/google"
import "./globals.css";
import {cn} from "@/lib/utils";
import {SessionProvider} from "next-auth/react";
import {TanstackQueryProvider} from "@/components/tanstack-query-provider";
import {Navbar} from "@/components/navbar/navbar";

const inter = Inter({
    subsets: ["latin"],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={cn(
                "bg-background font-sans antialiased",
                inter.className
            )}
        >
        <SessionProvider>
            <TanstackQueryProvider>
                <div className="xs:pb-[45px] relative flex min-h-screen flex-col">
                    <div className="main bg-white" vaul-drawer-wrapper="" style={{height: 'calc(100dvh - 4rem - 20px)'}}>
                        {children}
                    </div>
                    <Navbar/>
                </div>
            </TanstackQueryProvider>
        </SessionProvider>
        </body>
        </html>
);
}
